name: GInGeR CI

on: 
  push:

jobs:
  build-and-test-package:
    strategy:
      fail-fast: true 
      matrix:
        os: ["ubuntu-latest"]
        include:
          - os: ubuntu-latest
            environment-file: ginger.yml
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    # - name: Run formatter
    #   uses: psf/black@stable
      # if: matrix.os == 'ubuntu-latest'
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.6'
    # - name: Run linter
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install flake8 pytest
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install dependencies on ${{ matrix.os }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: ginger_env
        environment-file: ${{ matrix.environment-file }}
        python-version: "3.11.6"
        auto-activate-base: false
    - name: Install ginger
      shell: bash -l {0}
      run: python -m pip install .
    - name: Run tests on ${{ matrix.os }}
      shell: bash -l {0}
      # run: python tests/e2e_test.py 
      run: python -m unittest discover -s tests