set -e
true
true
/sci/labs/morani/morani/icore-data/lab/Tools/personal_condas/Netta/miniforge3/envs/ginger_314/bin/spades-hammer /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/corrected/configs/config.info
/sci/labs/morani/morani/icore-data/lab/Tools/personal_condas/Netta/miniforge3/envs/ginger_314/bin/python3 /sci/labs/morani/morani/icore-data/lab/Tools/personal_condas/Netta/miniforge3/envs/ginger_314/share/spades/spades_pipeline/scripts/compress_all.py --input_file /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/corrected/corrected.yaml --ext_python_modules_home /sci/labs/morani/morani/icore-data/lab/Tools/personal_condas/Netta/miniforge3/envs/ginger_314/share/spades --max_threads 1 --output_dir /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/corrected --gzip_output
true
true
/sci/labs/morani/morani/icore-data/lab/Tools/personal_condas/Netta/miniforge3/envs/ginger_314/bin/spades-core /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/K21/configs/config.info /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/K21/configs/mda_mode.info /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/K21/configs/meta_mode.info
/sci/labs/morani/morani/icore-data/lab/Tools/personal_condas/Netta/miniforge3/envs/ginger_314/bin/spades-core /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/K33/configs/config.info /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/K33/configs/mda_mode.info /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/K33/configs/meta_mode.info
/sci/labs/morani/morani/icore-data/lab/Tools/personal_condas/Netta/miniforge3/envs/ginger_314/bin/spades-core /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/K55/configs/config.info /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/K55/configs/mda_mode.info /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/K55/configs/meta_mode.info
/sci/labs/morani/morani/icore-data/lab/Tools/personal_condas/Netta/miniforge3/envs/ginger_314/bin/python3 /sci/labs/morani/morani/icore-data/lab/Tools/personal_condas/Netta/miniforge3/envs/ginger_314/share/spades/spades_pipeline/scripts/copy_files.py /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/K55/before_rr.fasta /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/before_rr.fasta /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/K55/assembly_graph_after_simplification.gfa /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/assembly_graph_after_simplification.gfa /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/K55/final_contigs.fasta /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/contigs.fasta /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/K55/first_pe_contigs.fasta /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/first_pe_contigs.fasta /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/K55/strain_graph.gfa /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/strain_graph.gfa /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/K55/scaffolds.fasta /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/scaffolds.fasta /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/K55/scaffolds.paths /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/scaffolds.paths /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/K55/assembly_graph_with_scaffolds.gfa /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/assembly_graph_with_scaffolds.gfa /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/K55/assembly_graph.fastg /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/assembly_graph.fastg /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/K55/final_contigs.paths /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/contigs.paths
true
/sci/labs/morani/morani/icore-data/lab/Tools/personal_condas/Netta/miniforge3/envs/ginger_314/bin/python3 /sci/labs/morani/morani/icore-data/lab/Tools/personal_condas/Netta/miniforge3/envs/ginger_314/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/scaffolds.fasta --misc_dir /sci/backup/morani/lab/Projects/GInGeR/GInGeR/e2e_test_output/SPAdes/misc --threshold_for_breaking_scaffolds 3
true
