set -e
true
true
/cs/usr/netta.barak/.conda/envs/evaluating_ginger/bin/spades-hammer /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/corrected/configs/config.info
/cs/usr/netta.barak/.conda/envs/evaluating_ginger/bin/python /cs/usr/netta.barak/.conda/envs/evaluating_ginger/share/spades/spades_pipeline/scripts/compress_all.py --input_file /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/corrected/corrected.yaml --ext_python_modules_home /cs/usr/netta.barak/.conda/envs/evaluating_ginger/share/spades --max_threads 1 --output_dir /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/corrected --gzip_output
true
true
/cs/usr/netta.barak/.conda/envs/evaluating_ginger/bin/spades-core /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/K21/configs/config.info /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/K21/configs/mda_mode.info /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/K21/configs/meta_mode.info
/cs/usr/netta.barak/.conda/envs/evaluating_ginger/bin/spades-core /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/K33/configs/config.info /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/K33/configs/mda_mode.info /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/K33/configs/meta_mode.info
/cs/usr/netta.barak/.conda/envs/evaluating_ginger/bin/spades-core /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/K55/configs/config.info /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/K55/configs/mda_mode.info /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/K55/configs/meta_mode.info
/cs/usr/netta.barak/.conda/envs/evaluating_ginger/bin/python /cs/usr/netta.barak/.conda/envs/evaluating_ginger/share/spades/spades_pipeline/scripts/copy_files.py /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/K55/before_rr.fasta /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/before_rr.fasta /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/K55/assembly_graph_after_simplification.gfa /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/assembly_graph_after_simplification.gfa /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/K55/final_contigs.fasta /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/contigs.fasta /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/K55/first_pe_contigs.fasta /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/first_pe_contigs.fasta /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/K55/strain_graph.gfa /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/strain_graph.gfa /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/K55/scaffolds.fasta /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/scaffolds.fasta /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/K55/scaffolds.paths /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/scaffolds.paths /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/K55/assembly_graph_with_scaffolds.gfa /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/assembly_graph_with_scaffolds.gfa /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/K55/assembly_graph.fastg /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/assembly_graph.fastg /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/K55/final_contigs.paths /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/contigs.paths
true
/cs/usr/netta.barak/.conda/envs/evaluating_ginger/bin/python /cs/usr/netta.barak/.conda/envs/evaluating_ginger/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/scaffolds.fasta --misc_dir /sci/labs/morani/morani/icore-data/lab/Projects/hybrid_assembler/GInGeR/e2e_test_output/SPAdes/misc --threshold_for_breaking_scaffolds 3
true
